title:  Южный Речной Порт
email: urport@superuser.su
description: >
    Открытое акционерное общество «Южный речной порт» является крупным транспортным предприятием, 
    имеющим успешный опыт во всех сферах работ, осуществляемых на внутренних речных путях Российской Федерации
baseurl: "/"
url: "https://urport.ru"

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
